### ISSUE TITLE
Getting js error when parsing markdown

### ISSUE THREAD

**Issue by flatoy** [GonzaloHirsch/nuxt-blog-starter#1]
Tried to clone and run this example but i'm getting an error from the markdown front-matter

```
[11:27:53 PM] [nuxt] [request error] [unhandled] [500] Cannot use 'in' operator to search for 'children' in Sample excerpt, appears in blog cards
```

caused by the excerpt parameter in the markdown documents

```
---
title: "Sample Meta Title | Blog"
description: "Sample meta description, it gets added on share cards"
headline: "Sample Blog Title"
excerpt: "Sample excerpt, appears in blog cards"
date: "2023-02-28T12:00:00"
dateUpdated: ""
...
---
```

**Comment by flatoy** [comment]
seems like the `@nuxt/content` package is doing excerpts in a [special way](https://content.nuxtjs.org/v1/getting-started/writing#excerpt), so specifying that parameter in the front-matter doesn't work. 

I just changed it to `summary` instead of `excerpt` and it worked 👍 

thanks for the awesome blog example ❤️

**Comment by GonzaloHirsch** [comment]
> seems like the `@nuxt/content` package is doing excerpts in a [special way](https://content.nuxtjs.org/v1/getting-started/writing#excerpt), so specifying that parameter in the front-matter doesn't work.
> 
> I just changed it to `summary` instead of `excerpt` and it worked 👍
> 
> thanks for the awesome blog example ❤️

Can you share how to replicate the issue? I haven't experienced that issue and have used this starter extensively.

On another note, if you want to extend this starter, I have a bunch of tutorials on the topic. See this [post](https://gonzalohirsch.com/blog/dark-mode-with-tailwind-css-in-nuxt-3/) for instance.

I'm glad you find it useful!

**Comment by flatoy** [comment]
I tried to clone again and run `pnpm install` and this time is worked fine. I don't know what happened the first time 🤷‍♂️
